# Generated by Django 5.2.16 on 2026-07-17 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0004_alter_etablissement_type_etablissement_and_more"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QCM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("date_ouverture", models.DateTimeField(blank=True, null=True)),
                ("date_limite", models.DateTimeField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qcms",
                        to="academics.classe",
                    ),
                ),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qcms_crees",
                        to="accounts.enseignant",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qcms",
                        to="academics.matiere",
                    ),
                ),
            ],
            options={
                "verbose_name": "QCM",
                "verbose_name_plural": "QCM",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="QuestionQCM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte", models.CharField(max_length=500)),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                (
                    "points",
                    models.DecimalField(decimal_places=1, default=1, max_digits=4),
                ),
                (
                    "qcm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="qcm.qcm",
                    ),
                ),
            ],
            options={
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="ChoixQCM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte", models.CharField(max_length=255)),
                ("est_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choix",
                        to="qcm.questionqcm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TentativeQCM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateTimeField(auto_now_add=True)),
                ("date_soumission", models.DateTimeField(blank=True, null=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tentatives_qcm",
                        to="accounts.eleve",
                    ),
                ),
                (
                    "qcm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tentatives",
                        to="qcm.qcm",
                    ),
                ),
            ],
            options={
                "unique_together": {("qcm", "eleve")},
            },
        ),
        migrations.CreateModel(
            name="ReponseEleve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="qcm.choixqcm",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="qcm.questionqcm",
                    ),
                ),
                (
                    "tentative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="qcm.tentativeqcm",
                    ),
                ),
            ],
            options={
                "unique_together": {("tentative", "question")},
            },
        ),
    ]
