# Generated by Django 5.2.16 on 2026-07-17 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ressource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "type_ressource",
                    models.CharField(
                        choices=[("SALLE", "Salle"), ("MATERIEL", "Matériel")],
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("motif", models.CharField(blank=True, max_length=255)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "creneau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations_ressources",
                        to="timetable.creneauhoraire",
                    ),
                ),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations_ressources",
                        to="accounts.enseignant",
                    ),
                ),
                (
                    "ressource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="ressources.ressource",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "creneau__ordre"],
                "unique_together": {("ressource", "date", "creneau")},
            },
        ),
    ]
