# Generated by Django 5.2.16 on 2026-07-18 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_backfill_etablissement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlerteDecrochage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score_risque", models.PositiveSmallIntegerField()),
                (
                    "signaux",
                    models.JSONField(
                        default=list,
                        help_text="Liste des signaux détectés : [{type, description}].",
                    ),
                ),
                ("date_detection", models.DateTimeField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("NOUVELLE", "Nouvelle"),
                            ("EN_COURS", "Prise en charge"),
                            ("RESOLUE", "Résolue"),
                        ],
                        default="NOUVELLE",
                        max_length=10,
                    ),
                ),
                ("notes_suivi", models.TextField(blank=True)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertes_decrochage",
                        to="accounts.eleve",
                    ),
                ),
                (
                    "traite_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertes_traitees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte de décrochage",
                "verbose_name_plural": "Alertes de décrochage",
                "ordering": ["-score_risque", "-date_detection"],
            },
        ),
    ]
