# Generated by Django 5.2.16 on 2026-07-17 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisponibiliteRDV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disponibilites",
                        to="accounts.enseignant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disponibilité de rendez-vous",
                "verbose_name_plural": "Disponibilités de rendez-vous",
                "ordering": ["date", "heure_debut"],
                "unique_together": {("enseignant", "date", "heure_debut")},
            },
        ),
        migrations.CreateModel(
            name="RendezVous",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motif", models.CharField(blank=True, max_length=255)),
                ("date_demande", models.DateTimeField(auto_now_add=True)),
                (
                    "disponibilite",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rendez_vous",
                        to="rendezvous.disponibiliterdv",
                    ),
                ),
                (
                    "eleve_concerne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rendez_vous",
                        to="accounts.eleve",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rendez_vous",
                        to="accounts.parent",
                    ),
                ),
            ],
        ),
    ]
