# Generated by Django 5.2.16 on 2026-07-18 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0007_etablissement_slug"),
        ("accounts", "0004_utilisateur_langue_notifications"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FraisScolarite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        help_text='Ex: "Frais d\'inscription", "Trimestre 1"',
                        max_length=150,
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_echeance", models.DateField()),
                (
                    "annee_scolaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frais_scolarite",
                        to="academics.anneescolaire",
                    ),
                ),
                (
                    "niveau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frais_scolarite",
                        to="academics.niveau",
                    ),
                ),
            ],
            options={
                "verbose_name": "Frais de scolarité",
                "verbose_name_plural": "Frais de scolarité",
                "ordering": ["date_echeance"],
            },
        ),
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("PARTIELLEMENT_PAYEE", "Partiellement payée"),
                            ("PAYEE", "Payée"),
                            ("EN_RETARD", "En retard"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factures",
                        to="accounts.eleve",
                    ),
                ),
                (
                    "frais",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factures",
                        to="finance.fraisscolarite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "ordering": ["-date_creation"],
                "unique_together": {("eleve", "frais")},
            },
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_paiement", models.DateField()),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("ESPECES", "Espèces"),
                            ("VIREMENT", "Virement"),
                            ("CHEQUE", "Chèque"),
                            ("CCP", "CCP"),
                        ],
                        default="ESPECES",
                        max_length=10,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=100)),
                (
                    "numero_recu",
                    models.CharField(editable=False, max_length=40, unique=True),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="finance.facture",
                    ),
                ),
                (
                    "saisi_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paiements_saisis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "ordering": ["-date_paiement"],
            },
        ),
    ]
