# Generated by Django 5.2.16 on 2026-07-18 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0008_groupescolaire_etablissement_groupe"),
        ("accounts", "0005_utilisateur_groupe_gere"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowRegle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                (
                    "declencheur",
                    models.CharField(
                        choices=[
                            ("NOTE_BASSE", "Note en dessous d'un seuil"),
                            ("RETARDS_FREQUENTS", "Retards fréquents"),
                            ("DEVOIR_NON_RENDU", "Devoir non rendu après échéance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "seuil",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Note seuil sur 20 (NOTE_BASSE), nombre de retards (RETARDS_FREQUENTS) ou jours de retard (DEVOIR_NON_RENDU), selon le déclencheur.",
                        max_digits=5,
                    ),
                ),
                (
                    "destinataire",
                    models.CharField(
                        choices=[
                            ("PARENT", "Parent(s) de l'élève"),
                            ("PROF_PRINCIPAL", "Professeur principal"),
                        ],
                        default="PARENT",
                        max_length=15,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        default='Une règle automatique ("{regle}") a été déclenchée pour {eleve}.',
                        help_text="Variables disponibles : {regle}, {eleve}, {seuil}, et selon le déclencheur {matiere}/{valeur} (NOTE_BASSE), {nb_retards} (RETARDS_FREQUENTS), {devoir} (DEVOIR_NON_RENDU).",
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                (
                    "etablissement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regles_workflow",
                        to="academics.etablissement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Règle de workflow",
                "verbose_name_plural": "Règles de workflow",
            },
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cle_unicite", models.CharField(max_length=100)),
                ("date_execution", models.DateTimeField(auto_now_add=True)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions_workflow",
                        to="accounts.eleve",
                    ),
                ),
                (
                    "regle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="workflows.workflowregle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exécution de règle",
                "verbose_name_plural": "Exécutions de règles",
                "ordering": ["-date_execution"],
                "unique_together": {("regle", "eleve", "cle_unicite")},
            },
        ),
    ]
