# Generated by Django 5.2.16 on 2026-07-17 13:59

import admissions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0007_etablissement_slug"),
        ("accounts", "0003_backfill_etablissement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        default=admissions.models._generer_reference,
                        editable=False,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("date_naissance", models.DateField(blank=True, null=True)),
                (
                    "sexe",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculin"), ("F", "Féminin")],
                        max_length=1,
                    ),
                ),
                ("nom_parent", models.CharField(max_length=150)),
                ("telephone_parent", models.CharField(max_length=20)),
                ("email_parent", models.EmailField(max_length=254)),
                ("adresse", models.CharField(blank=True, max_length=255)),
                (
                    "bulletin_precedent",
                    models.FileField(
                        blank=True, null=True, upload_to="admissions/bulletins/"
                    ),
                ),
                (
                    "acte_naissance",
                    models.FileField(
                        blank=True, null=True, upload_to="admissions/actes_naissance/"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="admissions/photos/"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("RECU", "Reçue"),
                            ("EN_EXAMEN", "En cours d'examen"),
                            ("ACCEPTE", "Acceptée"),
                            ("REFUSE", "Refusée"),
                            ("LISTE_ATTENTE", "Liste d'attente"),
                        ],
                        default="RECU",
                        max_length=15,
                    ),
                ),
                (
                    "notes_admin",
                    models.TextField(
                        blank=True,
                        help_text="Notes internes, jamais visibles par la famille.",
                    ),
                ),
                ("date_soumission", models.DateTimeField(auto_now_add=True)),
                ("date_traitement", models.DateTimeField(blank=True, null=True)),
                (
                    "eleve_cree",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidature_origine",
                        to="accounts.eleve",
                    ),
                ),
                (
                    "etablissement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidatures",
                        to="academics.etablissement",
                    ),
                ),
                (
                    "niveau_souhaite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidatures",
                        to="academics.niveau",
                    ),
                ),
                (
                    "traite_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidatures_traitees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidature",
                "verbose_name_plural": "Candidatures",
                "ordering": ["-date_soumission"],
            },
        ),
    ]
