# Generated by Django 5.2.16 on 2026-07-17 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=150)),
                (
                    "type_evaluation",
                    models.CharField(
                        choices=[
                            ("DEVOIR", "Devoir"),
                            ("INTERROGATION", "Interrogation"),
                            ("COMPOSITION", "Composition"),
                        ],
                        default="DEVOIR",
                        max_length=15,
                    ),
                ),
                (
                    "coefficient_evaluation",
                    models.DecimalField(decimal_places=1, default=1, max_digits=4),
                ),
                ("date_evaluation", models.DateField()),
                (
                    "bareme",
                    models.DecimalField(decimal_places=1, default=20, max_digits=4),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="academics.classe",
                    ),
                ),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="accounts.enseignant",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="academics.matiere",
                    ),
                ),
                (
                    "trimestre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="academics.trimestre",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_evaluation"],
            },
        ),
        migrations.CreateModel(
            name="AppreciationGenerale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte", models.TextField(blank=True)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appreciations_generales",
                        to="accounts.eleve",
                    ),
                ),
                (
                    "redigee_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appreciations_generales_redigees",
                        to="accounts.enseignant",
                    ),
                ),
                (
                    "trimestre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appreciations_generales",
                        to="academics.trimestre",
                    ),
                ),
            ],
            options={
                "unique_together": {("eleve", "trimestre")},
            },
        ),
        migrations.CreateModel(
            name="AppreciationMatiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte", models.TextField(blank=True)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appreciations_matiere",
                        to="accounts.eleve",
                    ),
                ),
                (
                    "enseignant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appreciations_donnees",
                        to="accounts.enseignant",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appreciations",
                        to="academics.matiere",
                    ),
                ),
                (
                    "trimestre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appreciations_matiere",
                        to="academics.trimestre",
                    ),
                ),
            ],
            options={
                "unique_together": {("eleve", "matiere", "trimestre")},
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valeur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Vide = absent / non noté",
                        max_digits=4,
                        null=True,
                    ),
                ),
                ("commentaire", models.CharField(blank=True, max_length=255)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="accounts.eleve",
                    ),
                ),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="grades.evaluation",
                    ),
                ),
            ],
            options={
                "unique_together": {("evaluation", "eleve")},
            },
        ),
    ]
