# Generated by Django 5.2.16 on 2026-07-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_backfill_etablissement"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="langue_notifications",
            field=models.CharField(
                choices=[("fr", "Français"), ("ar", "العربية")],
                default="fr",
                help_text="Langue utilisée pour le rapport hebdomadaire et les notifications par email.",
                max_length=2,
            ),
        ),
    ]
