# Generated by Django 5.2.16 on 2026-07-18 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0008_groupescolaire_etablissement_groupe"),
        ("accounts", "0004_utilisateur_langue_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="groupe_gere",
            field=models.ForeignKey(
                blank=True,
                help_text="Si renseigné, cet administrateur voit le tableau de bord consolidé de tous les campus du groupe.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="administrateurs",
                to="academics.groupescolaire",
            ),
        ),
    ]
