# Generated by Django 5.2.16 on 2026-07-18 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0007_etablissement_slug"),
        ("accounts", "0003_backfill_etablissement"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnaleExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.CharField(help_text='Ex: "2025"', max_length=20)),
                ("titre", models.CharField(max_length=200)),
                (
                    "fichier",
                    models.FileField(blank=True, null=True, upload_to="annales/"),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annales",
                        to="academics.matiere",
                    ),
                ),
                (
                    "niveau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annales",
                        to="academics.niveau",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annale d'examen",
                "verbose_name_plural": "Annales d'examen",
                "ordering": ["-annee"],
            },
        ),
        migrations.CreateModel(
            name="ProgrammeChapitre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordre", models.PositiveSmallIntegerField(default=1)),
                ("titre", models.CharField(max_length=200)),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapitres_programme",
                        to="academics.matiere",
                    ),
                ),
                (
                    "niveau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapitres_programme",
                        to="academics.niveau",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chapitre du programme",
                "verbose_name_plural": "Chapitres du programme",
                "ordering": ["niveau", "matiere", "ordre"],
                "unique_together": {("niveau", "matiere", "ordre")},
            },
        ),
        migrations.CreateModel(
            name="DateExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_examen", models.DateField()),
                (
                    "annee_scolaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dates_examen",
                        to="academics.anneescolaire",
                    ),
                ),
                (
                    "niveau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dates_examen",
                        to="academics.niveau",
                    ),
                ),
            ],
            options={
                "verbose_name": "Date d'examen",
                "verbose_name_plural": "Dates d'examen",
                "unique_together": {("niveau", "annee_scolaire")},
            },
        ),
        migrations.CreateModel(
            name="ProgressionChapitre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("A_FAIRE", "À faire"),
                            ("EN_COURS", "En cours"),
                            ("MAITRISE", "Maîtrisé"),
                        ],
                        default="A_FAIRE",
                        max_length=10,
                    ),
                ),
                ("date_maj", models.DateTimeField(auto_now=True)),
                (
                    "chapitre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progressions",
                        to="revisions.programmechapitre",
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progressions_revision",
                        to="accounts.eleve",
                    ),
                ),
            ],
            options={
                "unique_together": {("eleve", "chapitre")},
            },
        ),
    ]
