# Generated by Django 5.2.16 on 2026-07-17 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("fichier", models.FileField(upload_to="documents/")),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("REGLEMENT", "Règlement intérieur"),
                            ("SUPPORT_COURS", "Support de cours"),
                            ("ADMINISTRATIF", "Administratif"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=20,
                    ),
                ),
                ("date_depot", models.DateTimeField(auto_now_add=True)),
                (
                    "classe",
                    models.ForeignKey(
                        blank=True,
                        help_text="Laisser vide pour un document visible par tout l'établissement.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="academics.classe",
                    ),
                ),
                (
                    "depose_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_deposes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_depot"],
            },
        ),
    ]
