# Generated by Django 5.2.16 on 2026-07-17 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        ("accounts", "0001_initial"),
        ("attendance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CahierDeTexte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenu", models.TextField()),
                ("date_saisie", models.DateTimeField(auto_now_add=True)),
                ("visible_eleves", models.BooleanField(default=True)),
                (
                    "saisi_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cahiers_saisis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cahier_de_texte",
                        to="attendance.seance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cahier de texte",
                "verbose_name_plural": "Cahier de texte",
            },
        ),
        migrations.CreateModel(
            name="Devoir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_a_faire_pour", models.DateField()),
                ("consigne", models.TextField()),
                (
                    "piece_jointe",
                    models.FileField(blank=True, null=True, upload_to="devoirs/"),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devoirs",
                        to="academics.classe",
                    ),
                ),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devoirs_donnes",
                        to="accounts.enseignant",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devoirs",
                        to="academics.matiere",
                    ),
                ),
                (
                    "seance_donnee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devoirs_donnes",
                        to="attendance.seance",
                    ),
                ),
            ],
            options={
                "ordering": ["date_a_faire_pour"],
            },
        ),
    ]
