# Generated by Django 5.2.16 on 2026-07-17 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("homework", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RenduDevoir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fichier", models.FileField(upload_to="rendus_devoirs/")),
                ("date_soumission", models.DateTimeField(auto_now_add=True)),
                (
                    "note_sur_20",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("commentaire_correction", models.TextField(blank=True)),
                ("corrige_le", models.DateTimeField(blank=True, null=True)),
                (
                    "corrige_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rendus_corriges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "devoir",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rendus",
                        to="homework.devoir",
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devoirs_rendus",
                        to="accounts.eleve",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devoir rendu",
                "verbose_name_plural": "Devoirs rendus",
                "ordering": ["-date_soumission"],
                "unique_together": {("devoir", "eleve")},
            },
        ),
    ]
