# Generated by Django 5.2.16 on 2026-07-17 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreneauHoraire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jour_semaine",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Dimanche"),
                            (1, "Lundi"),
                            (2, "Mardi"),
                            (3, "Mercredi"),
                            (4, "Jeudi"),
                            (5, "Samedi"),
                        ]
                    ),
                ),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                (
                    "ordre",
                    models.PositiveSmallIntegerField(
                        help_text="Rang du créneau dans la journée"
                    ),
                ),
            ],
            options={
                "verbose_name": "Créneau horaire",
                "verbose_name_plural": "Créneaux horaires",
                "ordering": ["jour_semaine", "ordre"],
                "unique_together": {("jour_semaine", "ordre")},
            },
        ),
        migrations.CreateModel(
            name="EmploiDuTempsEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annee_scolaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emploi_du_temps",
                        to="academics.anneescolaire",
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emploi_du_temps",
                        to="academics.classe",
                    ),
                ),
                (
                    "creneau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrees",
                        to="timetable.creneauhoraire",
                    ),
                ),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emploi_du_temps",
                        to="accounts.enseignant",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emploi_du_temps",
                        to="academics.matiere",
                    ),
                ),
                (
                    "salle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emploi_du_temps",
                        to="academics.salle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrée d'emploi du temps",
                "verbose_name_plural": "Emploi du temps",
                "unique_together": {
                    ("classe", "creneau", "annee_scolaire"),
                    ("enseignant", "creneau", "annee_scolaire"),
                    ("salle", "creneau", "annee_scolaire"),
                },
            },
        ),
    ]
