# Generated by Django 5.2.16 on 2026-07-18 02:19

import assistant_ia.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0007_etablissement_slug"),
        ("accounts", "0003_backfill_etablissement"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plafond_mensuel_tokens",
                    models.PositiveIntegerField(
                        default=200000,
                        help_text="Nombre maximum de tokens IA consommés par mois pour cet établissement.",
                    ),
                ),
                ("tokens_utilises", models.PositiveIntegerField(default=0)),
                (
                    "mois_courant",
                    models.CharField(
                        default=assistant_ia.models._mois_courant,
                        help_text='Format "YYYY-MM".',
                        max_length=7,
                    ),
                ),
                (
                    "etablissement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_ia",
                        to="academics.etablissement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget IA",
                "verbose_name_plural": "Budgets IA",
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(default="Nouvelle conversation", max_length=150),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations_ia",
                        to="accounts.eleve",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="MessageConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("UTILISATEUR", "Élève"), ("ASSISTANT", "Assistant")],
                        max_length=15,
                    ),
                ),
                ("contenu", models.TextField()),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("tokens_utilises", models.PositiveIntegerField(default=0)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="assistant_ia.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["date_creation"],
            },
        ),
    ]
