# Generated by Django 5.2.16 on 2026-07-17 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionSondage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte", models.CharField(max_length=255)),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="ChoixReponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte", models.CharField(max_length=150)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choix",
                        to="sondages.questionsondage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sondage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("TOUS", "Tout l'établissement"),
                            ("ENSEIGNANTS", "Enseignants"),
                            ("ELEVES", "Élèves"),
                            ("PARENTS", "Parents"),
                        ],
                        default="TOUS",
                        max_length=15,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_cloture", models.DateField(blank=True, null=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sondages_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_creation"],
            },
        ),
        migrations.AddField(
            model_name="questionsondage",
            name="sondage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="sondages.sondage",
            ),
        ),
        migrations.CreateModel(
            name="ReponseUtilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_reponse", models.DateTimeField(auto_now_add=True)),
                (
                    "choix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="sondages.choixreponse",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="sondages.questionsondage",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses_sondages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("question", "utilisateur")},
            },
        ),
    ]
