# Generated by Django 5.2.16 on 2026-07-17 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("contenu", models.TextField()),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("TOUS", "Tout l'établissement"),
                            ("ENSEIGNANTS", "Enseignants"),
                            ("ELEVES_PARENTS", "Élèves et parents"),
                        ],
                        default="TOUS",
                        max_length=20,
                    ),
                ),
                ("epingle", models.BooleanField(default=False)),
                ("date_publication", models.DateTimeField(auto_now_add=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-epingle", "-date_publication"],
            },
        ),
    ]
