# Generated by Django 5.2.16 on 2026-07-17 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_salle_etablissement"),
        ("actualites", "0002_lectureaccusee"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="etablissement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publications",
                to="academics.etablissement",
            ),
        ),
    ]
