# Generated by Django 5.2.16 on 2026-07-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actualites", "0003_publication_etablissement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="audience",
            field=models.CharField(
                choices=[
                    ("TOUS", "Tout l'établissement"),
                    ("ENSEIGNANTS", "Enseignants"),
                    ("ELEVES_PARENTS", "Élèves et parents"),
                    ("PUBLIC", "Portail public (visiteurs)"),
                ],
                default="TOUS",
                max_length=20,
            ),
        ),
    ]
