/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedArchiveRouteImport } from './routes/_authenticated/archive'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedReferralRouteImport } from './routes/_authenticated/referral'
import { Route as AuthenticatedArchiveIndexRouteImport } from './routes/_authenticated/archive.index'
import { Route as AuthenticatedArchiveSubmitRouteImport } from './routes/_authenticated/archive.submit'
import { Route as AuthenticatedCommunityIndexRouteImport } from './routes/_authenticated/community.index'
import { Route as AuthenticatedCommunityThreadIdRouteImport } from './routes/_authenticated/community.$threadId'
import { Route as AuthenticatedCoursesIndexRouteImport } from './routes/_authenticated/courses.index'
import { Route as AuthenticatedCoursesCourseIdRouteImport } from './routes/_authenticated/courses.$courseId'
import { Route as AuthenticatedGroupsIndexRouteImport } from './routes/_authenticated/groups.index'
import { Route as AuthenticatedGroupsGroupIdRouteImport } from './routes/_authenticated/groups.$groupId'
import { Route as AuthenticatedLibraryIndexRouteImport } from './routes/_authenticated/library.index'
import { Route as AuthenticatedLiveSessionIdRouteImport } from './routes/_authenticated/live.$sessionId'
import { Route as AuthenticatedPaymentCancelRouteImport } from './routes/_authenticated/payment.cancel'
import { Route as AuthenticatedPaymentSuccessRouteImport } from './routes/_authenticated/payment.success'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks.index'
import { Route as AuthenticatedTeacherIndexRouteImport } from './routes/_authenticated/teacher.index'
import { Route as AuthenticatedTeacherAvailabilityRouteImport } from './routes/_authenticated/teacher.availability'
import { Route as AuthenticatedTeachersIndexRouteImport } from './routes/_authenticated/teachers.index'
import { Route as AuthenticatedTeachersTeacherIdRouteImport } from './routes/_authenticated/teachers.$teacherId'
import { Route as AuthenticatedToolsIndexRouteImport } from './routes/_authenticated/tools.index'
import { Route as AuthenticatedToolsCalculatorRouteImport } from './routes/_authenticated/tools.calculator'
import { Route as AuthenticatedToolsCountdownRouteImport } from './routes/_authenticated/tools.countdown'
import { Route as AuthenticatedToolsHomeworkRouteImport } from './routes/_authenticated/tools.homework'
import { Route as AuthenticatedArchiveExamTypeIndexRouteImport } from './routes/_authenticated/archive.$examType.index'
import { Route as AuthenticatedArchiveExamTypeSubjectRouteImport } from './routes/_authenticated/archive.$examType.$subject'
import { Route as AuthenticatedLibraryCycleIndexRouteImport } from './routes/_authenticated/library.$cycle.index'
import { Route as AuthenticatedSessionsBookTeacherIdRouteImport } from './routes/_authenticated/sessions.book.$teacherId'
import { Route as AuthenticatedTeacherCoursesIndexRouteImport } from './routes/_authenticated/teacher.courses.index'
import { Route as AuthenticatedTeacherCoursesCourseIdRouteImport } from './routes/_authenticated/teacher.courses.$courseId'
import { Route as AuthenticatedTeacherCoursesNewRouteImport } from './routes/_authenticated/teacher.courses.new'
import { Route as AuthenticatedToolsMemoIndexRouteImport } from './routes/_authenticated/tools.memo.index'
import { Route as AuthenticatedToolsMemoSheetIdRouteImport } from './routes/_authenticated/tools.memo.$sheetId'
import { Route as AuthenticatedLibraryCycleLevelSlugIndexRouteImport } from './routes/_authenticated/library.$cycle.$levelSlug.index'
import { Route as AuthenticatedLibraryCycleLevelSlugSubjectSlugRouteImport } from './routes/_authenticated/library.$cycle.$levelSlug.$subjectSlug'
import { Route as AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRouteImport } from './routes/_authenticated/library.$cycle.$levelSlug.$subjectSlug.$chapterId'
import { Route as AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdLessonIdRouteImport } from './routes/_authenticated/library.$cycle.$levelSlug.$subjectSlug.$chapterId.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchiveRoute = AuthenticatedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralRoute = AuthenticatedReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchiveIndexRoute =
  AuthenticatedArchiveIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedArchiveRoute,
  } as any)
const AuthenticatedArchiveSubmitRoute =
  AuthenticatedArchiveSubmitRouteImport.update({
    id: '/submit',
    path: '/submit',
    getParentRoute: () => AuthenticatedArchiveRoute,
  } as any)
const AuthenticatedCommunityIndexRoute =
  AuthenticatedCommunityIndexRouteImport.update({
    id: '/community/',
    path: '/community/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommunityThreadIdRoute =
  AuthenticatedCommunityThreadIdRouteImport.update({
    id: '/community/$threadId',
    path: '/community/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesIndexRoute =
  AuthenticatedCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdRoute =
  AuthenticatedCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupsGroupIdRoute =
  AuthenticatedGroupsGroupIdRouteImport.update({
    id: '/groups/$groupId',
    path: '/groups/$groupId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibraryIndexRoute =
  AuthenticatedLibraryIndexRouteImport.update({
    id: '/library/',
    path: '/library/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLiveSessionIdRoute =
  AuthenticatedLiveSessionIdRouteImport.update({
    id: '/live/$sessionId',
    path: '/live/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentCancelRoute =
  AuthenticatedPaymentCancelRouteImport.update({
    id: '/payment/cancel',
    path: '/payment/cancel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentSuccessRoute =
  AuthenticatedPaymentSuccessRouteImport.update({
    id: '/payment/success',
    path: '/payment/success',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeacherIndexRoute =
  AuthenticatedTeacherIndexRouteImport.update({
    id: '/teacher/',
    path: '/teacher/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherAvailabilityRoute =
  AuthenticatedTeacherAvailabilityRouteImport.update({
    id: '/teacher/availability',
    path: '/teacher/availability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeachersIndexRoute =
  AuthenticatedTeachersIndexRouteImport.update({
    id: '/teachers/',
    path: '/teachers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeachersTeacherIdRoute =
  AuthenticatedTeachersTeacherIdRouteImport.update({
    id: '/teachers/$teacherId',
    path: '/teachers/$teacherId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsIndexRoute = AuthenticatedToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolsCalculatorRoute =
  AuthenticatedToolsCalculatorRouteImport.update({
    id: '/tools/calculator',
    path: '/tools/calculator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsCountdownRoute =
  AuthenticatedToolsCountdownRouteImport.update({
    id: '/tools/countdown',
    path: '/tools/countdown',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsHomeworkRoute =
  AuthenticatedToolsHomeworkRouteImport.update({
    id: '/tools/homework',
    path: '/tools/homework',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArchiveExamTypeIndexRoute =
  AuthenticatedArchiveExamTypeIndexRouteImport.update({
    id: '/$examType/',
    path: '/$examType/',
    getParentRoute: () => AuthenticatedArchiveRoute,
  } as any)
const AuthenticatedArchiveExamTypeSubjectRoute =
  AuthenticatedArchiveExamTypeSubjectRouteImport.update({
    id: '/$examType/$subject',
    path: '/$examType/$subject',
    getParentRoute: () => AuthenticatedArchiveRoute,
  } as any)
const AuthenticatedLibraryCycleIndexRoute =
  AuthenticatedLibraryCycleIndexRouteImport.update({
    id: '/library/$cycle/',
    path: '/library/$cycle/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionsBookTeacherIdRoute =
  AuthenticatedSessionsBookTeacherIdRouteImport.update({
    id: '/sessions/book/$teacherId',
    path: '/sessions/book/$teacherId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherCoursesIndexRoute =
  AuthenticatedTeacherCoursesIndexRouteImport.update({
    id: '/teacher/courses/',
    path: '/teacher/courses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherCoursesCourseIdRoute =
  AuthenticatedTeacherCoursesCourseIdRouteImport.update({
    id: '/teacher/courses/$courseId',
    path: '/teacher/courses/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherCoursesNewRoute =
  AuthenticatedTeacherCoursesNewRouteImport.update({
    id: '/teacher/courses/new',
    path: '/teacher/courses/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsMemoIndexRoute =
  AuthenticatedToolsMemoIndexRouteImport.update({
    id: '/tools/memo/',
    path: '/tools/memo/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsMemoSheetIdRoute =
  AuthenticatedToolsMemoSheetIdRouteImport.update({
    id: '/tools/memo/$sheetId',
    path: '/tools/memo/$sheetId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibraryCycleLevelSlugIndexRoute =
  AuthenticatedLibraryCycleLevelSlugIndexRouteImport.update({
    id: '/library/$cycle/$levelSlug/',
    path: '/library/$cycle/$levelSlug/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibraryCycleLevelSlugSubjectSlugRoute =
  AuthenticatedLibraryCycleLevelSlugSubjectSlugRouteImport.update({
    id: '/library/$cycle/$levelSlug/$subjectSlug',
    path: '/library/$cycle/$levelSlug/$subjectSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRoute =
  AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRouteImport.update({
    id: '/$chapterId',
    path: '/$chapterId',
    getParentRoute: () => AuthenticatedLibraryCycleLevelSlugSubjectSlugRoute,
  } as any)
const AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdLessonIdRoute =
  AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdLessonIdRouteImport.update(
    {
      id: '/$lessonId',
      path: '/$lessonId',
      getParentRoute: () =>
        AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai': typeof AuthenticatedAiRoute
  '/archive': typeof AuthenticatedArchiveRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/archive/submit': typeof AuthenticatedArchiveSubmitRoute
  '/community/$threadId': typeof AuthenticatedCommunityThreadIdRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/live/$sessionId': typeof AuthenticatedLiveSessionIdRoute
  '/payment/cancel': typeof AuthenticatedPaymentCancelRoute
  '/payment/success': typeof AuthenticatedPaymentSuccessRoute
  '/teacher/availability': typeof AuthenticatedTeacherAvailabilityRoute
  '/teachers/$teacherId': typeof AuthenticatedTeachersTeacherIdRoute
  '/tools/calculator': typeof AuthenticatedToolsCalculatorRoute
  '/tools/countdown': typeof AuthenticatedToolsCountdownRoute
  '/tools/homework': typeof AuthenticatedToolsHomeworkRoute
  '/archive/': typeof AuthenticatedArchiveIndexRoute
  '/community/': typeof AuthenticatedCommunityIndexRoute
  '/courses/': typeof AuthenticatedCoursesIndexRoute
  '/groups/': typeof AuthenticatedGroupsIndexRoute
  '/library/': typeof AuthenticatedLibraryIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/teachers/': typeof AuthenticatedTeachersIndexRoute
  '/tools/': typeof AuthenticatedToolsIndexRoute
  '/archive/$examType/$subject': typeof AuthenticatedArchiveExamTypeSubjectRoute
  '/sessions/book/$teacherId': typeof AuthenticatedSessionsBookTeacherIdRoute
  '/teacher/courses/$courseId': typeof AuthenticatedTeacherCoursesCourseIdRoute
  '/teacher/courses/new': typeof AuthenticatedTeacherCoursesNewRoute
  '/tools/memo/$sheetId': typeof AuthenticatedToolsMemoSheetIdRoute
  '/archive/$examType/': typeof AuthenticatedArchiveExamTypeIndexRoute
  '/library/$cycle/': typeof AuthenticatedLibraryCycleIndexRoute
  '/teacher/courses/': typeof AuthenticatedTeacherCoursesIndexRoute
  '/tools/memo/': typeof AuthenticatedToolsMemoIndexRoute
  '/library/$cycle/$levelSlug/$subjectSlug': typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugRouteWithChildren
  '/library/$cycle/$levelSlug/': typeof AuthenticatedLibraryCycleLevelSlugIndexRoute
  '/library/$cycle/$levelSlug/$subjectSlug/$chapterId': typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRouteWithChildren
  '/library/$cycle/$levelSlug/$subjectSlug/$chapterId/$lessonId': typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai': typeof AuthenticatedAiRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/archive/submit': typeof AuthenticatedArchiveSubmitRoute
  '/community/$threadId': typeof AuthenticatedCommunityThreadIdRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/live/$sessionId': typeof AuthenticatedLiveSessionIdRoute
  '/payment/cancel': typeof AuthenticatedPaymentCancelRoute
  '/payment/success': typeof AuthenticatedPaymentSuccessRoute
  '/teacher/availability': typeof AuthenticatedTeacherAvailabilityRoute
  '/teachers/$teacherId': typeof AuthenticatedTeachersTeacherIdRoute
  '/tools/calculator': typeof AuthenticatedToolsCalculatorRoute
  '/tools/countdown': typeof AuthenticatedToolsCountdownRoute
  '/tools/homework': typeof AuthenticatedToolsHomeworkRoute
  '/archive': typeof AuthenticatedArchiveIndexRoute
  '/community': typeof AuthenticatedCommunityIndexRoute
  '/courses': typeof AuthenticatedCoursesIndexRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
  '/library': typeof AuthenticatedLibraryIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/teacher': typeof AuthenticatedTeacherIndexRoute
  '/teachers': typeof AuthenticatedTeachersIndexRoute
  '/tools': typeof AuthenticatedToolsIndexRoute
  '/archive/$examType/$subject': typeof AuthenticatedArchiveExamTypeSubjectRoute
  '/sessions/book/$teacherId': typeof AuthenticatedSessionsBookTeacherIdRoute
  '/teacher/courses/$courseId': typeof AuthenticatedTeacherCoursesCourseIdRoute
  '/teacher/courses/new': typeof AuthenticatedTeacherCoursesNewRoute
  '/tools/memo/$sheetId': typeof AuthenticatedToolsMemoSheetIdRoute
  '/archive/$examType': typeof AuthenticatedArchiveExamTypeIndexRoute
  '/library/$cycle': typeof AuthenticatedLibraryCycleIndexRoute
  '/teacher/courses': typeof AuthenticatedTeacherCoursesIndexRoute
  '/tools/memo': typeof AuthenticatedToolsMemoIndexRoute
  '/library/$cycle/$levelSlug/$subjectSlug': typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugRouteWithChildren
  '/library/$cycle/$levelSlug': typeof AuthenticatedLibraryCycleLevelSlugIndexRoute
  '/library/$cycle/$levelSlug/$subjectSlug/$chapterId': typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRouteWithChildren
  '/library/$cycle/$levelSlug/$subjectSlug/$chapterId/$lessonId': typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/archive': typeof AuthenticatedArchiveRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/referral': typeof AuthenticatedReferralRoute
  '/_authenticated/archive/submit': typeof AuthenticatedArchiveSubmitRoute
  '/_authenticated/community/$threadId': typeof AuthenticatedCommunityThreadIdRoute
  '/_authenticated/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/_authenticated/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/_authenticated/live/$sessionId': typeof AuthenticatedLiveSessionIdRoute
  '/_authenticated/payment/cancel': typeof AuthenticatedPaymentCancelRoute
  '/_authenticated/payment/success': typeof AuthenticatedPaymentSuccessRoute
  '/_authenticated/teacher/availability': typeof AuthenticatedTeacherAvailabilityRoute
  '/_authenticated/teachers/$teacherId': typeof AuthenticatedTeachersTeacherIdRoute
  '/_authenticated/tools/calculator': typeof AuthenticatedToolsCalculatorRoute
  '/_authenticated/tools/countdown': typeof AuthenticatedToolsCountdownRoute
  '/_authenticated/tools/homework': typeof AuthenticatedToolsHomeworkRoute
  '/_authenticated/archive/': typeof AuthenticatedArchiveIndexRoute
  '/_authenticated/community/': typeof AuthenticatedCommunityIndexRoute
  '/_authenticated/courses/': typeof AuthenticatedCoursesIndexRoute
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
  '/_authenticated/library/': typeof AuthenticatedLibraryIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/_authenticated/teachers/': typeof AuthenticatedTeachersIndexRoute
  '/_authenticated/tools/': typeof AuthenticatedToolsIndexRoute
  '/_authenticated/archive/$examType/$subject': typeof AuthenticatedArchiveExamTypeSubjectRoute
  '/_authenticated/sessions/book/$teacherId': typeof AuthenticatedSessionsBookTeacherIdRoute
  '/_authenticated/teacher/courses/$courseId': typeof AuthenticatedTeacherCoursesCourseIdRoute
  '/_authenticated/teacher/courses/new': typeof AuthenticatedTeacherCoursesNewRoute
  '/_authenticated/tools/memo/$sheetId': typeof AuthenticatedToolsMemoSheetIdRoute
  '/_authenticated/archive/$examType/': typeof AuthenticatedArchiveExamTypeIndexRoute
  '/_authenticated/library/$cycle/': typeof AuthenticatedLibraryCycleIndexRoute
  '/_authenticated/teacher/courses/': typeof AuthenticatedTeacherCoursesIndexRoute
  '/_authenticated/tools/memo/': typeof AuthenticatedToolsMemoIndexRoute
  '/_authenticated/library/$cycle/$levelSlug/$subjectSlug': typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugRouteWithChildren
  '/_authenticated/library/$cycle/$levelSlug/': typeof AuthenticatedLibraryCycleLevelSlugIndexRoute
  '/_authenticated/library/$cycle/$levelSlug/$subjectSlug/$chapterId': typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRouteWithChildren
  '/_authenticated/library/$cycle/$levelSlug/$subjectSlug/$chapterId/$lessonId': typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin'
    | '/ai'
    | '/archive'
    | '/dashboard'
    | '/referral'
    | '/archive/submit'
    | '/community/$threadId'
    | '/courses/$courseId'
    | '/groups/$groupId'
    | '/live/$sessionId'
    | '/payment/cancel'
    | '/payment/success'
    | '/teacher/availability'
    | '/teachers/$teacherId'
    | '/tools/calculator'
    | '/tools/countdown'
    | '/tools/homework'
    | '/archive/'
    | '/community/'
    | '/courses/'
    | '/groups/'
    | '/library/'
    | '/tasks/'
    | '/teacher/'
    | '/teachers/'
    | '/tools/'
    | '/archive/$examType/$subject'
    | '/sessions/book/$teacherId'
    | '/teacher/courses/$courseId'
    | '/teacher/courses/new'
    | '/tools/memo/$sheetId'
    | '/archive/$examType/'
    | '/library/$cycle/'
    | '/teacher/courses/'
    | '/tools/memo/'
    | '/library/$cycle/$levelSlug/$subjectSlug'
    | '/library/$cycle/$levelSlug/'
    | '/library/$cycle/$levelSlug/$subjectSlug/$chapterId'
    | '/library/$cycle/$levelSlug/$subjectSlug/$chapterId/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin'
    | '/ai'
    | '/dashboard'
    | '/referral'
    | '/archive/submit'
    | '/community/$threadId'
    | '/courses/$courseId'
    | '/groups/$groupId'
    | '/live/$sessionId'
    | '/payment/cancel'
    | '/payment/success'
    | '/teacher/availability'
    | '/teachers/$teacherId'
    | '/tools/calculator'
    | '/tools/countdown'
    | '/tools/homework'
    | '/archive'
    | '/community'
    | '/courses'
    | '/groups'
    | '/library'
    | '/tasks'
    | '/teacher'
    | '/teachers'
    | '/tools'
    | '/archive/$examType/$subject'
    | '/sessions/book/$teacherId'
    | '/teacher/courses/$courseId'
    | '/teacher/courses/new'
    | '/tools/memo/$sheetId'
    | '/archive/$examType'
    | '/library/$cycle'
    | '/teacher/courses'
    | '/tools/memo'
    | '/library/$cycle/$levelSlug/$subjectSlug'
    | '/library/$cycle/$levelSlug'
    | '/library/$cycle/$levelSlug/$subjectSlug/$chapterId'
    | '/library/$cycle/$levelSlug/$subjectSlug/$chapterId/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/admin'
    | '/_authenticated/ai'
    | '/_authenticated/archive'
    | '/_authenticated/dashboard'
    | '/_authenticated/referral'
    | '/_authenticated/archive/submit'
    | '/_authenticated/community/$threadId'
    | '/_authenticated/courses/$courseId'
    | '/_authenticated/groups/$groupId'
    | '/_authenticated/live/$sessionId'
    | '/_authenticated/payment/cancel'
    | '/_authenticated/payment/success'
    | '/_authenticated/teacher/availability'
    | '/_authenticated/teachers/$teacherId'
    | '/_authenticated/tools/calculator'
    | '/_authenticated/tools/countdown'
    | '/_authenticated/tools/homework'
    | '/_authenticated/archive/'
    | '/_authenticated/community/'
    | '/_authenticated/courses/'
    | '/_authenticated/groups/'
    | '/_authenticated/library/'
    | '/_authenticated/tasks/'
    | '/_authenticated/teacher/'
    | '/_authenticated/teachers/'
    | '/_authenticated/tools/'
    | '/_authenticated/archive/$examType/$subject'
    | '/_authenticated/sessions/book/$teacherId'
    | '/_authenticated/teacher/courses/$courseId'
    | '/_authenticated/teacher/courses/new'
    | '/_authenticated/tools/memo/$sheetId'
    | '/_authenticated/archive/$examType/'
    | '/_authenticated/library/$cycle/'
    | '/_authenticated/teacher/courses/'
    | '/_authenticated/tools/memo/'
    | '/_authenticated/library/$cycle/$levelSlug/$subjectSlug'
    | '/_authenticated/library/$cycle/$levelSlug/'
    | '/_authenticated/library/$cycle/$levelSlug/$subjectSlug/$chapterId'
    | '/_authenticated/library/$cycle/$levelSlug/$subjectSlug/$chapterId/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referral': {
      id: '/_authenticated/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof AuthenticatedReferralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive/': {
      id: '/_authenticated/archive/'
      path: '/'
      fullPath: '/archive/'
      preLoaderRoute: typeof AuthenticatedArchiveIndexRouteImport
      parentRoute: typeof AuthenticatedArchiveRoute
    }
    '/_authenticated/archive/submit': {
      id: '/_authenticated/archive/submit'
      path: '/submit'
      fullPath: '/archive/submit'
      preLoaderRoute: typeof AuthenticatedArchiveSubmitRouteImport
      parentRoute: typeof AuthenticatedArchiveRoute
    }
    '/_authenticated/community/': {
      id: '/_authenticated/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof AuthenticatedCommunityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community/$threadId': {
      id: '/_authenticated/community/$threadId'
      path: '/community/$threadId'
      fullPath: '/community/$threadId'
      preLoaderRoute: typeof AuthenticatedCommunityThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/': {
      id: '/_authenticated/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AuthenticatedCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/$courseId': {
      id: '/_authenticated/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/$groupId': {
      id: '/_authenticated/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AuthenticatedGroupsGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library/': {
      id: '/_authenticated/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof AuthenticatedLibraryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live/$sessionId': {
      id: '/_authenticated/live/$sessionId'
      path: '/live/$sessionId'
      fullPath: '/live/$sessionId'
      preLoaderRoute: typeof AuthenticatedLiveSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment/cancel': {
      id: '/_authenticated/payment/cancel'
      path: '/payment/cancel'
      fullPath: '/payment/cancel'
      preLoaderRoute: typeof AuthenticatedPaymentCancelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment/success': {
      id: '/_authenticated/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof AuthenticatedPaymentSuccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/': {
      id: '/_authenticated/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AuthenticatedTeacherIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/availability': {
      id: '/_authenticated/teacher/availability'
      path: '/teacher/availability'
      fullPath: '/teacher/availability'
      preLoaderRoute: typeof AuthenticatedTeacherAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers/': {
      id: '/_authenticated/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof AuthenticatedTeachersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers/$teacherId': {
      id: '/_authenticated/teachers/$teacherId'
      path: '/teachers/$teacherId'
      fullPath: '/teachers/$teacherId'
      preLoaderRoute: typeof AuthenticatedTeachersTeacherIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/': {
      id: '/_authenticated/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof AuthenticatedToolsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/calculator': {
      id: '/_authenticated/tools/calculator'
      path: '/tools/calculator'
      fullPath: '/tools/calculator'
      preLoaderRoute: typeof AuthenticatedToolsCalculatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/countdown': {
      id: '/_authenticated/tools/countdown'
      path: '/tools/countdown'
      fullPath: '/tools/countdown'
      preLoaderRoute: typeof AuthenticatedToolsCountdownRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/homework': {
      id: '/_authenticated/tools/homework'
      path: '/tools/homework'
      fullPath: '/tools/homework'
      preLoaderRoute: typeof AuthenticatedToolsHomeworkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive/$examType/': {
      id: '/_authenticated/archive/$examType/'
      path: '/$examType'
      fullPath: '/archive/$examType/'
      preLoaderRoute: typeof AuthenticatedArchiveExamTypeIndexRouteImport
      parentRoute: typeof AuthenticatedArchiveRoute
    }
    '/_authenticated/archive/$examType/$subject': {
      id: '/_authenticated/archive/$examType/$subject'
      path: '/$examType/$subject'
      fullPath: '/archive/$examType/$subject'
      preLoaderRoute: typeof AuthenticatedArchiveExamTypeSubjectRouteImport
      parentRoute: typeof AuthenticatedArchiveRoute
    }
    '/_authenticated/library/$cycle/': {
      id: '/_authenticated/library/$cycle/'
      path: '/library/$cycle'
      fullPath: '/library/$cycle/'
      preLoaderRoute: typeof AuthenticatedLibraryCycleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/book/$teacherId': {
      id: '/_authenticated/sessions/book/$teacherId'
      path: '/sessions/book/$teacherId'
      fullPath: '/sessions/book/$teacherId'
      preLoaderRoute: typeof AuthenticatedSessionsBookTeacherIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/courses/': {
      id: '/_authenticated/teacher/courses/'
      path: '/teacher/courses'
      fullPath: '/teacher/courses/'
      preLoaderRoute: typeof AuthenticatedTeacherCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/courses/$courseId': {
      id: '/_authenticated/teacher/courses/$courseId'
      path: '/teacher/courses/$courseId'
      fullPath: '/teacher/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedTeacherCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/courses/new': {
      id: '/_authenticated/teacher/courses/new'
      path: '/teacher/courses/new'
      fullPath: '/teacher/courses/new'
      preLoaderRoute: typeof AuthenticatedTeacherCoursesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/memo/': {
      id: '/_authenticated/tools/memo/'
      path: '/tools/memo'
      fullPath: '/tools/memo/'
      preLoaderRoute: typeof AuthenticatedToolsMemoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/memo/$sheetId': {
      id: '/_authenticated/tools/memo/$sheetId'
      path: '/tools/memo/$sheetId'
      fullPath: '/tools/memo/$sheetId'
      preLoaderRoute: typeof AuthenticatedToolsMemoSheetIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library/$cycle/$levelSlug/': {
      id: '/_authenticated/library/$cycle/$levelSlug/'
      path: '/library/$cycle/$levelSlug'
      fullPath: '/library/$cycle/$levelSlug/'
      preLoaderRoute: typeof AuthenticatedLibraryCycleLevelSlugIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library/$cycle/$levelSlug/$subjectSlug': {
      id: '/_authenticated/library/$cycle/$levelSlug/$subjectSlug'
      path: '/library/$cycle/$levelSlug/$subjectSlug'
      fullPath: '/library/$cycle/$levelSlug/$subjectSlug'
      preLoaderRoute: typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library/$cycle/$levelSlug/$subjectSlug/$chapterId': {
      id: '/_authenticated/library/$cycle/$levelSlug/$subjectSlug/$chapterId'
      path: '/$chapterId'
      fullPath: '/library/$cycle/$levelSlug/$subjectSlug/$chapterId'
      preLoaderRoute: typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRouteImport
      parentRoute: typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugRoute
    }
    '/_authenticated/library/$cycle/$levelSlug/$subjectSlug/$chapterId/$lessonId': {
      id: '/_authenticated/library/$cycle/$levelSlug/$subjectSlug/$chapterId/$lessonId'
      path: '/$lessonId'
      fullPath: '/library/$cycle/$levelSlug/$subjectSlug/$chapterId/$lessonId'
      preLoaderRoute: typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdLessonIdRouteImport
      parentRoute: typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRoute
    }
  }
}

interface AuthenticatedArchiveRouteChildren {
  AuthenticatedArchiveSubmitRoute: typeof AuthenticatedArchiveSubmitRoute
  AuthenticatedArchiveIndexRoute: typeof AuthenticatedArchiveIndexRoute
  AuthenticatedArchiveExamTypeSubjectRoute: typeof AuthenticatedArchiveExamTypeSubjectRoute
  AuthenticatedArchiveExamTypeIndexRoute: typeof AuthenticatedArchiveExamTypeIndexRoute
}

const AuthenticatedArchiveRouteChildren: AuthenticatedArchiveRouteChildren = {
  AuthenticatedArchiveSubmitRoute: AuthenticatedArchiveSubmitRoute,
  AuthenticatedArchiveIndexRoute: AuthenticatedArchiveIndexRoute,
  AuthenticatedArchiveExamTypeSubjectRoute:
    AuthenticatedArchiveExamTypeSubjectRoute,
  AuthenticatedArchiveExamTypeIndexRoute:
    AuthenticatedArchiveExamTypeIndexRoute,
}

const AuthenticatedArchiveRouteWithChildren =
  AuthenticatedArchiveRoute._addFileChildren(AuthenticatedArchiveRouteChildren)

interface AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRouteChildren {
  AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdLessonIdRoute: typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdLessonIdRoute
}

const AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRouteChildren: AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRouteChildren =
  {
    AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdLessonIdRoute:
      AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdLessonIdRoute,
  }

const AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRouteWithChildren =
  AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRoute._addFileChildren(
    AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRouteChildren,
  )

interface AuthenticatedLibraryCycleLevelSlugSubjectSlugRouteChildren {
  AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRoute: typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRouteWithChildren
}

const AuthenticatedLibraryCycleLevelSlugSubjectSlugRouteChildren: AuthenticatedLibraryCycleLevelSlugSubjectSlugRouteChildren =
  {
    AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRoute:
      AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRouteWithChildren,
  }

const AuthenticatedLibraryCycleLevelSlugSubjectSlugRouteWithChildren =
  AuthenticatedLibraryCycleLevelSlugSubjectSlugRoute._addFileChildren(
    AuthenticatedLibraryCycleLevelSlugSubjectSlugRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedArchiveRoute: typeof AuthenticatedArchiveRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedReferralRoute: typeof AuthenticatedReferralRoute
  AuthenticatedCommunityThreadIdRoute: typeof AuthenticatedCommunityThreadIdRoute
  AuthenticatedCoursesCourseIdRoute: typeof AuthenticatedCoursesCourseIdRoute
  AuthenticatedGroupsGroupIdRoute: typeof AuthenticatedGroupsGroupIdRoute
  AuthenticatedLiveSessionIdRoute: typeof AuthenticatedLiveSessionIdRoute
  AuthenticatedPaymentCancelRoute: typeof AuthenticatedPaymentCancelRoute
  AuthenticatedPaymentSuccessRoute: typeof AuthenticatedPaymentSuccessRoute
  AuthenticatedTeacherAvailabilityRoute: typeof AuthenticatedTeacherAvailabilityRoute
  AuthenticatedTeachersTeacherIdRoute: typeof AuthenticatedTeachersTeacherIdRoute
  AuthenticatedToolsCalculatorRoute: typeof AuthenticatedToolsCalculatorRoute
  AuthenticatedToolsCountdownRoute: typeof AuthenticatedToolsCountdownRoute
  AuthenticatedToolsHomeworkRoute: typeof AuthenticatedToolsHomeworkRoute
  AuthenticatedCommunityIndexRoute: typeof AuthenticatedCommunityIndexRoute
  AuthenticatedCoursesIndexRoute: typeof AuthenticatedCoursesIndexRoute
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
  AuthenticatedLibraryIndexRoute: typeof AuthenticatedLibraryIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedTeacherIndexRoute: typeof AuthenticatedTeacherIndexRoute
  AuthenticatedTeachersIndexRoute: typeof AuthenticatedTeachersIndexRoute
  AuthenticatedToolsIndexRoute: typeof AuthenticatedToolsIndexRoute
  AuthenticatedSessionsBookTeacherIdRoute: typeof AuthenticatedSessionsBookTeacherIdRoute
  AuthenticatedTeacherCoursesCourseIdRoute: typeof AuthenticatedTeacherCoursesCourseIdRoute
  AuthenticatedTeacherCoursesNewRoute: typeof AuthenticatedTeacherCoursesNewRoute
  AuthenticatedToolsMemoSheetIdRoute: typeof AuthenticatedToolsMemoSheetIdRoute
  AuthenticatedLibraryCycleIndexRoute: typeof AuthenticatedLibraryCycleIndexRoute
  AuthenticatedTeacherCoursesIndexRoute: typeof AuthenticatedTeacherCoursesIndexRoute
  AuthenticatedToolsMemoIndexRoute: typeof AuthenticatedToolsMemoIndexRoute
  AuthenticatedLibraryCycleLevelSlugSubjectSlugRoute: typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugRouteWithChildren
  AuthenticatedLibraryCycleLevelSlugIndexRoute: typeof AuthenticatedLibraryCycleLevelSlugIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedArchiveRoute: AuthenticatedArchiveRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedReferralRoute: AuthenticatedReferralRoute,
  AuthenticatedCommunityThreadIdRoute: AuthenticatedCommunityThreadIdRoute,
  AuthenticatedCoursesCourseIdRoute: AuthenticatedCoursesCourseIdRoute,
  AuthenticatedGroupsGroupIdRoute: AuthenticatedGroupsGroupIdRoute,
  AuthenticatedLiveSessionIdRoute: AuthenticatedLiveSessionIdRoute,
  AuthenticatedPaymentCancelRoute: AuthenticatedPaymentCancelRoute,
  AuthenticatedPaymentSuccessRoute: AuthenticatedPaymentSuccessRoute,
  AuthenticatedTeacherAvailabilityRoute: AuthenticatedTeacherAvailabilityRoute,
  AuthenticatedTeachersTeacherIdRoute: AuthenticatedTeachersTeacherIdRoute,
  AuthenticatedToolsCalculatorRoute: AuthenticatedToolsCalculatorRoute,
  AuthenticatedToolsCountdownRoute: AuthenticatedToolsCountdownRoute,
  AuthenticatedToolsHomeworkRoute: AuthenticatedToolsHomeworkRoute,
  AuthenticatedCommunityIndexRoute: AuthenticatedCommunityIndexRoute,
  AuthenticatedCoursesIndexRoute: AuthenticatedCoursesIndexRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
  AuthenticatedLibraryIndexRoute: AuthenticatedLibraryIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedTeacherIndexRoute: AuthenticatedTeacherIndexRoute,
  AuthenticatedTeachersIndexRoute: AuthenticatedTeachersIndexRoute,
  AuthenticatedToolsIndexRoute: AuthenticatedToolsIndexRoute,
  AuthenticatedSessionsBookTeacherIdRoute:
    AuthenticatedSessionsBookTeacherIdRoute,
  AuthenticatedTeacherCoursesCourseIdRoute:
    AuthenticatedTeacherCoursesCourseIdRoute,
  AuthenticatedTeacherCoursesNewRoute: AuthenticatedTeacherCoursesNewRoute,
  AuthenticatedToolsMemoSheetIdRoute: AuthenticatedToolsMemoSheetIdRoute,
  AuthenticatedLibraryCycleIndexRoute: AuthenticatedLibraryCycleIndexRoute,
  AuthenticatedTeacherCoursesIndexRoute: AuthenticatedTeacherCoursesIndexRoute,
  AuthenticatedToolsMemoIndexRoute: AuthenticatedToolsMemoIndexRoute,
  AuthenticatedLibraryCycleLevelSlugSubjectSlugRoute:
    AuthenticatedLibraryCycleLevelSlugSubjectSlugRouteWithChildren,
  AuthenticatedLibraryCycleLevelSlugIndexRoute:
    AuthenticatedLibraryCycleLevelSlugIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
