/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedArchiveRouteImport } from './routes/_authenticated/archive'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedArchiveIndexRouteImport } from './routes/_authenticated/archive.index'
import { Route as AuthenticatedArchiveSubmitRouteImport } from './routes/_authenticated/archive.submit'
import { Route as AuthenticatedCoursesIndexRouteImport } from './routes/_authenticated/courses.index'
import { Route as AuthenticatedCoursesCourseIdRouteImport } from './routes/_authenticated/courses.$courseId'
import { Route as AuthenticatedLibraryIndexRouteImport } from './routes/_authenticated/library.index'
import { Route as AuthenticatedLiveSessionIdRouteImport } from './routes/_authenticated/live.$sessionId'
import { Route as AuthenticatedTeacherIndexRouteImport } from './routes/_authenticated/teacher.index'
import { Route as AuthenticatedTeacherAvailabilityRouteImport } from './routes/_authenticated/teacher.availability'
import { Route as AuthenticatedTeachersIndexRouteImport } from './routes/_authenticated/teachers.index'
import { Route as AuthenticatedTeachersTeacherIdRouteImport } from './routes/_authenticated/teachers.$teacherId'
import { Route as AuthenticatedArchiveExamTypeIndexRouteImport } from './routes/_authenticated/archive.$examType.index'
import { Route as AuthenticatedArchiveExamTypeSubjectRouteImport } from './routes/_authenticated/archive.$examType.$subject'
import { Route as AuthenticatedLibraryCycleIndexRouteImport } from './routes/_authenticated/library.$cycle.index'
import { Route as AuthenticatedSessionsBookTeacherIdRouteImport } from './routes/_authenticated/sessions.book.$teacherId'
import { Route as AuthenticatedTeacherCoursesIndexRouteImport } from './routes/_authenticated/teacher.courses.index'
import { Route as AuthenticatedTeacherCoursesCourseIdRouteImport } from './routes/_authenticated/teacher.courses.$courseId'
import { Route as AuthenticatedTeacherCoursesNewRouteImport } from './routes/_authenticated/teacher.courses.new'
import { Route as AuthenticatedLibraryCycleLevelSlugIndexRouteImport } from './routes/_authenticated/library.$cycle.$levelSlug.index'
import { Route as AuthenticatedLibraryCycleLevelSlugSubjectSlugRouteImport } from './routes/_authenticated/library.$cycle.$levelSlug.$subjectSlug'
import { Route as AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRouteImport } from './routes/_authenticated/library.$cycle.$levelSlug.$subjectSlug.$chapterId'
import { Route as AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdLessonIdRouteImport } from './routes/_authenticated/library.$cycle.$levelSlug.$subjectSlug.$chapterId.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchiveRoute = AuthenticatedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchiveIndexRoute =
  AuthenticatedArchiveIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedArchiveRoute,
  } as any)
const AuthenticatedArchiveSubmitRoute =
  AuthenticatedArchiveSubmitRouteImport.update({
    id: '/submit',
    path: '/submit',
    getParentRoute: () => AuthenticatedArchiveRoute,
  } as any)
const AuthenticatedCoursesIndexRoute =
  AuthenticatedCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdRoute =
  AuthenticatedCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibraryIndexRoute =
  AuthenticatedLibraryIndexRouteImport.update({
    id: '/library/',
    path: '/library/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLiveSessionIdRoute =
  AuthenticatedLiveSessionIdRouteImport.update({
    id: '/live/$sessionId',
    path: '/live/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherIndexRoute =
  AuthenticatedTeacherIndexRouteImport.update({
    id: '/teacher/',
    path: '/teacher/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherAvailabilityRoute =
  AuthenticatedTeacherAvailabilityRouteImport.update({
    id: '/teacher/availability',
    path: '/teacher/availability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeachersIndexRoute =
  AuthenticatedTeachersIndexRouteImport.update({
    id: '/teachers/',
    path: '/teachers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeachersTeacherIdRoute =
  AuthenticatedTeachersTeacherIdRouteImport.update({
    id: '/teachers/$teacherId',
    path: '/teachers/$teacherId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArchiveExamTypeIndexRoute =
  AuthenticatedArchiveExamTypeIndexRouteImport.update({
    id: '/$examType/',
    path: '/$examType/',
    getParentRoute: () => AuthenticatedArchiveRoute,
  } as any)
const AuthenticatedArchiveExamTypeSubjectRoute =
  AuthenticatedArchiveExamTypeSubjectRouteImport.update({
    id: '/$examType/$subject',
    path: '/$examType/$subject',
    getParentRoute: () => AuthenticatedArchiveRoute,
  } as any)
const AuthenticatedLibraryCycleIndexRoute =
  AuthenticatedLibraryCycleIndexRouteImport.update({
    id: '/library/$cycle/',
    path: '/library/$cycle/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionsBookTeacherIdRoute =
  AuthenticatedSessionsBookTeacherIdRouteImport.update({
    id: '/sessions/book/$teacherId',
    path: '/sessions/book/$teacherId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherCoursesIndexRoute =
  AuthenticatedTeacherCoursesIndexRouteImport.update({
    id: '/teacher/courses/',
    path: '/teacher/courses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherCoursesCourseIdRoute =
  AuthenticatedTeacherCoursesCourseIdRouteImport.update({
    id: '/teacher/courses/$courseId',
    path: '/teacher/courses/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherCoursesNewRoute =
  AuthenticatedTeacherCoursesNewRouteImport.update({
    id: '/teacher/courses/new',
    path: '/teacher/courses/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibraryCycleLevelSlugIndexRoute =
  AuthenticatedLibraryCycleLevelSlugIndexRouteImport.update({
    id: '/library/$cycle/$levelSlug/',
    path: '/library/$cycle/$levelSlug/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibraryCycleLevelSlugSubjectSlugRoute =
  AuthenticatedLibraryCycleLevelSlugSubjectSlugRouteImport.update({
    id: '/library/$cycle/$levelSlug/$subjectSlug',
    path: '/library/$cycle/$levelSlug/$subjectSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRoute =
  AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRouteImport.update({
    id: '/$chapterId',
    path: '/$chapterId',
    getParentRoute: () => AuthenticatedLibraryCycleLevelSlugSubjectSlugRoute,
  } as any)
const AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdLessonIdRoute =
  AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdLessonIdRouteImport.update(
    {
      id: '/$lessonId',
      path: '/$lessonId',
      getParentRoute: () =>
        AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai': typeof AuthenticatedAiRoute
  '/archive': typeof AuthenticatedArchiveRouteWithChildren
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/archive/submit': typeof AuthenticatedArchiveSubmitRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/live/$sessionId': typeof AuthenticatedLiveSessionIdRoute
  '/teacher/availability': typeof AuthenticatedTeacherAvailabilityRoute
  '/teachers/$teacherId': typeof AuthenticatedTeachersTeacherIdRoute
  '/archive/': typeof AuthenticatedArchiveIndexRoute
  '/courses/': typeof AuthenticatedCoursesIndexRoute
  '/library/': typeof AuthenticatedLibraryIndexRoute
  '/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/teachers/': typeof AuthenticatedTeachersIndexRoute
  '/archive/$examType/$subject': typeof AuthenticatedArchiveExamTypeSubjectRoute
  '/sessions/book/$teacherId': typeof AuthenticatedSessionsBookTeacherIdRoute
  '/teacher/courses/$courseId': typeof AuthenticatedTeacherCoursesCourseIdRoute
  '/teacher/courses/new': typeof AuthenticatedTeacherCoursesNewRoute
  '/archive/$examType/': typeof AuthenticatedArchiveExamTypeIndexRoute
  '/library/$cycle/': typeof AuthenticatedLibraryCycleIndexRoute
  '/teacher/courses/': typeof AuthenticatedTeacherCoursesIndexRoute
  '/library/$cycle/$levelSlug/$subjectSlug': typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugRouteWithChildren
  '/library/$cycle/$levelSlug/': typeof AuthenticatedLibraryCycleLevelSlugIndexRoute
  '/library/$cycle/$levelSlug/$subjectSlug/$chapterId': typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRouteWithChildren
  '/library/$cycle/$levelSlug/$subjectSlug/$chapterId/$lessonId': typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai': typeof AuthenticatedAiRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/archive/submit': typeof AuthenticatedArchiveSubmitRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/live/$sessionId': typeof AuthenticatedLiveSessionIdRoute
  '/teacher/availability': typeof AuthenticatedTeacherAvailabilityRoute
  '/teachers/$teacherId': typeof AuthenticatedTeachersTeacherIdRoute
  '/archive': typeof AuthenticatedArchiveIndexRoute
  '/courses': typeof AuthenticatedCoursesIndexRoute
  '/library': typeof AuthenticatedLibraryIndexRoute
  '/teacher': typeof AuthenticatedTeacherIndexRoute
  '/teachers': typeof AuthenticatedTeachersIndexRoute
  '/archive/$examType/$subject': typeof AuthenticatedArchiveExamTypeSubjectRoute
  '/sessions/book/$teacherId': typeof AuthenticatedSessionsBookTeacherIdRoute
  '/teacher/courses/$courseId': typeof AuthenticatedTeacherCoursesCourseIdRoute
  '/teacher/courses/new': typeof AuthenticatedTeacherCoursesNewRoute
  '/archive/$examType': typeof AuthenticatedArchiveExamTypeIndexRoute
  '/library/$cycle': typeof AuthenticatedLibraryCycleIndexRoute
  '/teacher/courses': typeof AuthenticatedTeacherCoursesIndexRoute
  '/library/$cycle/$levelSlug/$subjectSlug': typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugRouteWithChildren
  '/library/$cycle/$levelSlug': typeof AuthenticatedLibraryCycleLevelSlugIndexRoute
  '/library/$cycle/$levelSlug/$subjectSlug/$chapterId': typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRouteWithChildren
  '/library/$cycle/$levelSlug/$subjectSlug/$chapterId/$lessonId': typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/archive': typeof AuthenticatedArchiveRouteWithChildren
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
  '/_authenticated/archive/submit': typeof AuthenticatedArchiveSubmitRoute
  '/_authenticated/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/_authenticated/live/$sessionId': typeof AuthenticatedLiveSessionIdRoute
  '/_authenticated/teacher/availability': typeof AuthenticatedTeacherAvailabilityRoute
  '/_authenticated/teachers/$teacherId': typeof AuthenticatedTeachersTeacherIdRoute
  '/_authenticated/archive/': typeof AuthenticatedArchiveIndexRoute
  '/_authenticated/courses/': typeof AuthenticatedCoursesIndexRoute
  '/_authenticated/library/': typeof AuthenticatedLibraryIndexRoute
  '/_authenticated/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/_authenticated/teachers/': typeof AuthenticatedTeachersIndexRoute
  '/_authenticated/archive/$examType/$subject': typeof AuthenticatedArchiveExamTypeSubjectRoute
  '/_authenticated/sessions/book/$teacherId': typeof AuthenticatedSessionsBookTeacherIdRoute
  '/_authenticated/teacher/courses/$courseId': typeof AuthenticatedTeacherCoursesCourseIdRoute
  '/_authenticated/teacher/courses/new': typeof AuthenticatedTeacherCoursesNewRoute
  '/_authenticated/archive/$examType/': typeof AuthenticatedArchiveExamTypeIndexRoute
  '/_authenticated/library/$cycle/': typeof AuthenticatedLibraryCycleIndexRoute
  '/_authenticated/teacher/courses/': typeof AuthenticatedTeacherCoursesIndexRoute
  '/_authenticated/library/$cycle/$levelSlug/$subjectSlug': typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugRouteWithChildren
  '/_authenticated/library/$cycle/$levelSlug/': typeof AuthenticatedLibraryCycleLevelSlugIndexRoute
  '/_authenticated/library/$cycle/$levelSlug/$subjectSlug/$chapterId': typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRouteWithChildren
  '/_authenticated/library/$cycle/$levelSlug/$subjectSlug/$chapterId/$lessonId': typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin'
    | '/ai'
    | '/archive'
    | '/community'
    | '/dashboard'
    | '/groups'
    | '/tools'
    | '/archive/submit'
    | '/courses/$courseId'
    | '/live/$sessionId'
    | '/teacher/availability'
    | '/teachers/$teacherId'
    | '/archive/'
    | '/courses/'
    | '/library/'
    | '/teacher/'
    | '/teachers/'
    | '/archive/$examType/$subject'
    | '/sessions/book/$teacherId'
    | '/teacher/courses/$courseId'
    | '/teacher/courses/new'
    | '/archive/$examType/'
    | '/library/$cycle/'
    | '/teacher/courses/'
    | '/library/$cycle/$levelSlug/$subjectSlug'
    | '/library/$cycle/$levelSlug/'
    | '/library/$cycle/$levelSlug/$subjectSlug/$chapterId'
    | '/library/$cycle/$levelSlug/$subjectSlug/$chapterId/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin'
    | '/ai'
    | '/community'
    | '/dashboard'
    | '/groups'
    | '/tools'
    | '/archive/submit'
    | '/courses/$courseId'
    | '/live/$sessionId'
    | '/teacher/availability'
    | '/teachers/$teacherId'
    | '/archive'
    | '/courses'
    | '/library'
    | '/teacher'
    | '/teachers'
    | '/archive/$examType/$subject'
    | '/sessions/book/$teacherId'
    | '/teacher/courses/$courseId'
    | '/teacher/courses/new'
    | '/archive/$examType'
    | '/library/$cycle'
    | '/teacher/courses'
    | '/library/$cycle/$levelSlug/$subjectSlug'
    | '/library/$cycle/$levelSlug'
    | '/library/$cycle/$levelSlug/$subjectSlug/$chapterId'
    | '/library/$cycle/$levelSlug/$subjectSlug/$chapterId/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/admin'
    | '/_authenticated/ai'
    | '/_authenticated/archive'
    | '/_authenticated/community'
    | '/_authenticated/dashboard'
    | '/_authenticated/groups'
    | '/_authenticated/tools'
    | '/_authenticated/archive/submit'
    | '/_authenticated/courses/$courseId'
    | '/_authenticated/live/$sessionId'
    | '/_authenticated/teacher/availability'
    | '/_authenticated/teachers/$teacherId'
    | '/_authenticated/archive/'
    | '/_authenticated/courses/'
    | '/_authenticated/library/'
    | '/_authenticated/teacher/'
    | '/_authenticated/teachers/'
    | '/_authenticated/archive/$examType/$subject'
    | '/_authenticated/sessions/book/$teacherId'
    | '/_authenticated/teacher/courses/$courseId'
    | '/_authenticated/teacher/courses/new'
    | '/_authenticated/archive/$examType/'
    | '/_authenticated/library/$cycle/'
    | '/_authenticated/teacher/courses/'
    | '/_authenticated/library/$cycle/$levelSlug/$subjectSlug'
    | '/_authenticated/library/$cycle/$levelSlug/'
    | '/_authenticated/library/$cycle/$levelSlug/$subjectSlug/$chapterId'
    | '/_authenticated/library/$cycle/$levelSlug/$subjectSlug/$chapterId/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive/': {
      id: '/_authenticated/archive/'
      path: '/'
      fullPath: '/archive/'
      preLoaderRoute: typeof AuthenticatedArchiveIndexRouteImport
      parentRoute: typeof AuthenticatedArchiveRoute
    }
    '/_authenticated/archive/submit': {
      id: '/_authenticated/archive/submit'
      path: '/submit'
      fullPath: '/archive/submit'
      preLoaderRoute: typeof AuthenticatedArchiveSubmitRouteImport
      parentRoute: typeof AuthenticatedArchiveRoute
    }
    '/_authenticated/courses/': {
      id: '/_authenticated/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AuthenticatedCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/$courseId': {
      id: '/_authenticated/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library/': {
      id: '/_authenticated/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof AuthenticatedLibraryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live/$sessionId': {
      id: '/_authenticated/live/$sessionId'
      path: '/live/$sessionId'
      fullPath: '/live/$sessionId'
      preLoaderRoute: typeof AuthenticatedLiveSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/': {
      id: '/_authenticated/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AuthenticatedTeacherIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/availability': {
      id: '/_authenticated/teacher/availability'
      path: '/teacher/availability'
      fullPath: '/teacher/availability'
      preLoaderRoute: typeof AuthenticatedTeacherAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers/': {
      id: '/_authenticated/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof AuthenticatedTeachersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers/$teacherId': {
      id: '/_authenticated/teachers/$teacherId'
      path: '/teachers/$teacherId'
      fullPath: '/teachers/$teacherId'
      preLoaderRoute: typeof AuthenticatedTeachersTeacherIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive/$examType/': {
      id: '/_authenticated/archive/$examType/'
      path: '/$examType'
      fullPath: '/archive/$examType/'
      preLoaderRoute: typeof AuthenticatedArchiveExamTypeIndexRouteImport
      parentRoute: typeof AuthenticatedArchiveRoute
    }
    '/_authenticated/archive/$examType/$subject': {
      id: '/_authenticated/archive/$examType/$subject'
      path: '/$examType/$subject'
      fullPath: '/archive/$examType/$subject'
      preLoaderRoute: typeof AuthenticatedArchiveExamTypeSubjectRouteImport
      parentRoute: typeof AuthenticatedArchiveRoute
    }
    '/_authenticated/library/$cycle/': {
      id: '/_authenticated/library/$cycle/'
      path: '/library/$cycle'
      fullPath: '/library/$cycle/'
      preLoaderRoute: typeof AuthenticatedLibraryCycleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/book/$teacherId': {
      id: '/_authenticated/sessions/book/$teacherId'
      path: '/sessions/book/$teacherId'
      fullPath: '/sessions/book/$teacherId'
      preLoaderRoute: typeof AuthenticatedSessionsBookTeacherIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/courses/': {
      id: '/_authenticated/teacher/courses/'
      path: '/teacher/courses'
      fullPath: '/teacher/courses/'
      preLoaderRoute: typeof AuthenticatedTeacherCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/courses/$courseId': {
      id: '/_authenticated/teacher/courses/$courseId'
      path: '/teacher/courses/$courseId'
      fullPath: '/teacher/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedTeacherCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/courses/new': {
      id: '/_authenticated/teacher/courses/new'
      path: '/teacher/courses/new'
      fullPath: '/teacher/courses/new'
      preLoaderRoute: typeof AuthenticatedTeacherCoursesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library/$cycle/$levelSlug/': {
      id: '/_authenticated/library/$cycle/$levelSlug/'
      path: '/library/$cycle/$levelSlug'
      fullPath: '/library/$cycle/$levelSlug/'
      preLoaderRoute: typeof AuthenticatedLibraryCycleLevelSlugIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library/$cycle/$levelSlug/$subjectSlug': {
      id: '/_authenticated/library/$cycle/$levelSlug/$subjectSlug'
      path: '/library/$cycle/$levelSlug/$subjectSlug'
      fullPath: '/library/$cycle/$levelSlug/$subjectSlug'
      preLoaderRoute: typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library/$cycle/$levelSlug/$subjectSlug/$chapterId': {
      id: '/_authenticated/library/$cycle/$levelSlug/$subjectSlug/$chapterId'
      path: '/$chapterId'
      fullPath: '/library/$cycle/$levelSlug/$subjectSlug/$chapterId'
      preLoaderRoute: typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRouteImport
      parentRoute: typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugRoute
    }
    '/_authenticated/library/$cycle/$levelSlug/$subjectSlug/$chapterId/$lessonId': {
      id: '/_authenticated/library/$cycle/$levelSlug/$subjectSlug/$chapterId/$lessonId'
      path: '/$lessonId'
      fullPath: '/library/$cycle/$levelSlug/$subjectSlug/$chapterId/$lessonId'
      preLoaderRoute: typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdLessonIdRouteImport
      parentRoute: typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRoute
    }
  }
}

interface AuthenticatedArchiveRouteChildren {
  AuthenticatedArchiveSubmitRoute: typeof AuthenticatedArchiveSubmitRoute
  AuthenticatedArchiveIndexRoute: typeof AuthenticatedArchiveIndexRoute
  AuthenticatedArchiveExamTypeSubjectRoute: typeof AuthenticatedArchiveExamTypeSubjectRoute
  AuthenticatedArchiveExamTypeIndexRoute: typeof AuthenticatedArchiveExamTypeIndexRoute
}

const AuthenticatedArchiveRouteChildren: AuthenticatedArchiveRouteChildren = {
  AuthenticatedArchiveSubmitRoute: AuthenticatedArchiveSubmitRoute,
  AuthenticatedArchiveIndexRoute: AuthenticatedArchiveIndexRoute,
  AuthenticatedArchiveExamTypeSubjectRoute:
    AuthenticatedArchiveExamTypeSubjectRoute,
  AuthenticatedArchiveExamTypeIndexRoute:
    AuthenticatedArchiveExamTypeIndexRoute,
}

const AuthenticatedArchiveRouteWithChildren =
  AuthenticatedArchiveRoute._addFileChildren(AuthenticatedArchiveRouteChildren)

interface AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRouteChildren {
  AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdLessonIdRoute: typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdLessonIdRoute
}

const AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRouteChildren: AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRouteChildren =
  {
    AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdLessonIdRoute:
      AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdLessonIdRoute,
  }

const AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRouteWithChildren =
  AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRoute._addFileChildren(
    AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRouteChildren,
  )

interface AuthenticatedLibraryCycleLevelSlugSubjectSlugRouteChildren {
  AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRoute: typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRouteWithChildren
}

const AuthenticatedLibraryCycleLevelSlugSubjectSlugRouteChildren: AuthenticatedLibraryCycleLevelSlugSubjectSlugRouteChildren =
  {
    AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRoute:
      AuthenticatedLibraryCycleLevelSlugSubjectSlugChapterIdRouteWithChildren,
  }

const AuthenticatedLibraryCycleLevelSlugSubjectSlugRouteWithChildren =
  AuthenticatedLibraryCycleLevelSlugSubjectSlugRoute._addFileChildren(
    AuthenticatedLibraryCycleLevelSlugSubjectSlugRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedArchiveRoute: typeof AuthenticatedArchiveRouteWithChildren
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
  AuthenticatedCoursesCourseIdRoute: typeof AuthenticatedCoursesCourseIdRoute
  AuthenticatedLiveSessionIdRoute: typeof AuthenticatedLiveSessionIdRoute
  AuthenticatedTeacherAvailabilityRoute: typeof AuthenticatedTeacherAvailabilityRoute
  AuthenticatedTeachersTeacherIdRoute: typeof AuthenticatedTeachersTeacherIdRoute
  AuthenticatedCoursesIndexRoute: typeof AuthenticatedCoursesIndexRoute
  AuthenticatedLibraryIndexRoute: typeof AuthenticatedLibraryIndexRoute
  AuthenticatedTeacherIndexRoute: typeof AuthenticatedTeacherIndexRoute
  AuthenticatedTeachersIndexRoute: typeof AuthenticatedTeachersIndexRoute
  AuthenticatedSessionsBookTeacherIdRoute: typeof AuthenticatedSessionsBookTeacherIdRoute
  AuthenticatedTeacherCoursesCourseIdRoute: typeof AuthenticatedTeacherCoursesCourseIdRoute
  AuthenticatedTeacherCoursesNewRoute: typeof AuthenticatedTeacherCoursesNewRoute
  AuthenticatedLibraryCycleIndexRoute: typeof AuthenticatedLibraryCycleIndexRoute
  AuthenticatedTeacherCoursesIndexRoute: typeof AuthenticatedTeacherCoursesIndexRoute
  AuthenticatedLibraryCycleLevelSlugSubjectSlugRoute: typeof AuthenticatedLibraryCycleLevelSlugSubjectSlugRouteWithChildren
  AuthenticatedLibraryCycleLevelSlugIndexRoute: typeof AuthenticatedLibraryCycleLevelSlugIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedArchiveRoute: AuthenticatedArchiveRouteWithChildren,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
  AuthenticatedCoursesCourseIdRoute: AuthenticatedCoursesCourseIdRoute,
  AuthenticatedLiveSessionIdRoute: AuthenticatedLiveSessionIdRoute,
  AuthenticatedTeacherAvailabilityRoute: AuthenticatedTeacherAvailabilityRoute,
  AuthenticatedTeachersTeacherIdRoute: AuthenticatedTeachersTeacherIdRoute,
  AuthenticatedCoursesIndexRoute: AuthenticatedCoursesIndexRoute,
  AuthenticatedLibraryIndexRoute: AuthenticatedLibraryIndexRoute,
  AuthenticatedTeacherIndexRoute: AuthenticatedTeacherIndexRoute,
  AuthenticatedTeachersIndexRoute: AuthenticatedTeachersIndexRoute,
  AuthenticatedSessionsBookTeacherIdRoute:
    AuthenticatedSessionsBookTeacherIdRoute,
  AuthenticatedTeacherCoursesCourseIdRoute:
    AuthenticatedTeacherCoursesCourseIdRoute,
  AuthenticatedTeacherCoursesNewRoute: AuthenticatedTeacherCoursesNewRoute,
  AuthenticatedLibraryCycleIndexRoute: AuthenticatedLibraryCycleIndexRoute,
  AuthenticatedTeacherCoursesIndexRoute: AuthenticatedTeacherCoursesIndexRoute,
  AuthenticatedLibraryCycleLevelSlugSubjectSlugRoute:
    AuthenticatedLibraryCycleLevelSlugSubjectSlugRouteWithChildren,
  AuthenticatedLibraryCycleLevelSlugIndexRoute:
    AuthenticatedLibraryCycleLevelSlugIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
