# Generated by Django 5.2.16 on 2026-07-17 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnneeScolaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        help_text='Ex: "2025-2026"', max_length=20, unique=True
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("est_active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Année scolaire",
                "verbose_name_plural": "Années scolaires",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="CoefficientMatiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coefficient", models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            options={
                "verbose_name": "Coefficient de matière",
                "verbose_name_plural": "Coefficients de matière",
            },
        ),
        migrations.CreateModel(
            name="Etablissement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("code", models.CharField(blank=True, max_length=30)),
                ("adresse", models.CharField(blank=True, max_length=255)),
                ("wilaya", models.CharField(blank=True, max_length=100)),
                ("commune", models.CharField(blank=True, max_length=100)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="etablissement/"
                    ),
                ),
                (
                    "type_etablissement",
                    models.CharField(
                        choices=[("COLLEGE", "Collège"), ("LYCEE", "Lycée")],
                        default="LYCEE",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Établissement",
            },
        ),
        migrations.CreateModel(
            name="Filiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        help_text='Ex: "Sciences", "Lettres et Philosophie"',
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Matiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=20)),
                (
                    "couleur",
                    models.CharField(
                        default="#2f5fa8",
                        help_text="Couleur hex pour l'emploi du temps",
                        max_length=7,
                    ),
                ),
            ],
            options={
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Niveau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(help_text='Ex: "1AS", "4AM"', max_length=50),
                ),
                (
                    "cycle",
                    models.CharField(
                        choices=[("COLLEGE", "Collège"), ("LYCEE", "Lycée")],
                        max_length=10,
                    ),
                ),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="Salle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("capacite", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("type_salle", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Trimestre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1er trimestre"),
                            (2, "2e trimestre"),
                            (3, "3e trimestre"),
                        ]
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("est_actif", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["annee_scolaire", "numero"],
            },
        ),
        migrations.CreateModel(
            name="Classe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(help_text='Ex: "1AS Sciences 2"', max_length=50),
                ),
                (
                    "effectif_max",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "annee_scolaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="academics.anneescolaire",
                    ),
                ),
            ],
            options={
                "ordering": ["niveau__ordre", "libelle"],
            },
        ),
    ]
