# Generated by Django 5.2.16 on 2026-07-17 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classe",
            name="professeur_principal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes_principal",
                to="accounts.enseignant",
            ),
        ),
        migrations.AddField(
            model_name="etablissement",
            name="annee_scolaire_courante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="academics.anneescolaire",
            ),
        ),
        migrations.AddField(
            model_name="coefficientmatiere",
            name="filiere",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coefficients_matieres",
                to="academics.filiere",
            ),
        ),
        migrations.AddField(
            model_name="classe",
            name="filiere",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes",
                to="academics.filiere",
            ),
        ),
        migrations.AddField(
            model_name="coefficientmatiere",
            name="matiere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coefficients",
                to="academics.matiere",
            ),
        ),
        migrations.AddField(
            model_name="coefficientmatiere",
            name="niveau",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coefficients_matieres",
                to="academics.niveau",
            ),
        ),
        migrations.AddField(
            model_name="classe",
            name="niveau",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classes",
                to="academics.niveau",
            ),
        ),
        migrations.AddField(
            model_name="trimestre",
            name="annee_scolaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trimestres",
                to="academics.anneescolaire",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="coefficientmatiere",
            unique_together={("matiere", "niveau", "filiere")},
        ),
        migrations.AlterUniqueTogether(
            name="classe",
            unique_together={("libelle", "annee_scolaire")},
        ),
        migrations.AlterUniqueTogether(
            name="trimestre",
            unique_together={("annee_scolaire", "numero")},
        ),
    ]
