# Generated by Django 5.2.16 on 2026-07-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matiere",
            name="couleur",
            field=models.CharField(
                default="#b8b0e8",
                help_text="Couleur hex pour l'emploi du temps",
                max_length=7,
            ),
        ),
    ]
