# Generated by Django 5.2.16 on 2026-07-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_alter_matiere_couleur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etablissement",
            name="type_etablissement",
            field=models.CharField(
                choices=[
                    ("PRIMAIRE", "École primaire"),
                    ("COLLEGE", "Collège (CEM)"),
                    ("LYCEE", "Lycée"),
                ],
                default="LYCEE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="niveau",
            name="cycle",
            field=models.CharField(
                choices=[
                    ("PRIMAIRE", "Primaire"),
                    ("MOYEN", "Moyen"),
                    ("SECONDAIRE", "Secondaire"),
                ],
                max_length=10,
            ),
        ),
    ]
