# Generated by Django 5.2.16 on 2026-07-17 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_alter_etablissement_type_etablissement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anneescolaire",
            name="etablissement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annees_scolaires",
                to="academics.etablissement",
            ),
        ),
        migrations.AlterField(
            model_name="anneescolaire",
            name="libelle",
            field=models.CharField(help_text='Ex: "2025-2026"', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="anneescolaire",
            unique_together={("etablissement", "libelle")},
        ),
    ]
