# Generated by Django 5.2.16 on 2026-07-17 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_anneescolaire_etablissement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salle",
            name="etablissement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salles",
                to="academics.etablissement",
            ),
        ),
    ]
