# Generated by Django 5.2.16 on 2026-07-18 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0007_etablissement_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupeScolaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("code", models.CharField(blank=True, max_length=30)),
            ],
            options={
                "verbose_name": "Groupe scolaire",
                "verbose_name_plural": "Groupes scolaires",
            },
        ),
        migrations.AddField(
            model_name="etablissement",
            name="groupe",
            field=models.ForeignKey(
                blank=True,
                help_text="Groupe scolaire auquel appartient ce campus, le cas échéant.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="etablissements",
                to="academics.groupescolaire",
            ),
        ),
    ]
