# Generated by Django 5.2.16 on 2026-07-17 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_notification",
                    models.CharField(
                        choices=[
                            ("ABSENCE", "Absence"),
                            ("NOTE", "Note publiée"),
                            ("MESSAGE", "Message reçu"),
                            ("INFO", "Information établissement"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=10,
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("contenu", models.TextField(blank=True)),
                (
                    "lien",
                    models.CharField(
                        blank=True,
                        help_text="URL relative vers laquelle rediriger au clic",
                        max_length=255,
                    ),
                ),
                ("lu", models.BooleanField(default=False)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_creation"],
            },
        ),
    ]
