# Generated by Django 5.2.16 on 2026-07-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type_notification",
            field=models.CharField(
                choices=[
                    ("ABSENCE", "Absence"),
                    ("NOTE", "Note publiée"),
                    ("MESSAGE", "Message reçu"),
                    ("INFO", "Information établissement"),
                    ("DECROCHAGE", "Alerte décrochage"),
                    ("AUTRE", "Autre"),
                ],
                default="AUTRE",
                max_length=10,
            ),
        ),
    ]
