# Generated by Django 5.2.16 on 2026-07-17 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Seance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("NORMALE", "Normale"),
                            ("ANNULEE", "Annulée"),
                            ("REMPLACEE", "Remplacée"),
                        ],
                        default="NORMALE",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Absence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("justifiee", models.BooleanField(default=False)),
                ("motif", models.CharField(blank=True, max_length=255)),
                ("date_saisie", models.DateTimeField(auto_now_add=True)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="accounts.eleve",
                    ),
                ),
                (
                    "saisie_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="absences_saisies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-seance__date"],
            },
        ),
        migrations.CreateModel(
            name="Retard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("heure_arrivee", models.TimeField()),
                ("duree_minutes", models.PositiveSmallIntegerField()),
                ("motif", models.CharField(blank=True, max_length=255)),
                ("justifie", models.BooleanField(default=False)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retards",
                        to="accounts.eleve",
                    ),
                ),
                (
                    "saisi_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retards_saisis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Justificatif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fichier", models.FileField(upload_to="justificatifs/")),
                ("commentaire", models.CharField(blank=True, max_length=255)),
                ("date_soumission", models.DateTimeField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("APPROUVE", "Approuvé"),
                            ("REJETE", "Rejeté"),
                        ],
                        default="EN_ATTENTE",
                        max_length=10,
                    ),
                ),
                (
                    "absence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="justificatifs",
                        to="attendance.absence",
                    ),
                ),
                (
                    "soumis_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="justificatifs_soumis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "traite_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="justificatifs_traites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "retard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="justificatifs",
                        to="attendance.retard",
                    ),
                ),
            ],
        ),
    ]
