# Generated by Django 5.2.16 on 2026-07-17 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("attendance", "0001_initial"),
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seance",
            name="emploi_du_temps_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seances",
                to="timetable.emploidutempsentry",
            ),
        ),
        migrations.AddField(
            model_name="seance",
            name="enseignant_remplacant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seances_remplacees",
                to="accounts.enseignant",
            ),
        ),
        migrations.AddField(
            model_name="absence",
            name="seance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="absences",
                to="attendance.seance",
            ),
        ),
        migrations.AddConstraint(
            model_name="justificatif",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("absence__isnull", False), ("retard__isnull", True)),
                    models.Q(("absence__isnull", True), ("retard__isnull", False)),
                    _connector="OR",
                ),
                name="justificatif_absence_xor_retard",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="seance",
            unique_together={("emploi_du_temps_entry", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="absence",
            unique_together={("seance", "eleve")},
        ),
    ]
